version: '{branch}-{build}'
build: off
environment:
  global:
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\ci\\appveyor-with-compiler.cmd"
  matrix:
    - TOXENV: "2.6"
      TOXPYTHON: "C:\\Python26\\python.exe"
      WINDOWS_SDK_VERSION: "v7.0"
      PYTHON_HOME: "C:\\Python26"
      PYTHON_VERSION: "2.6"
      PYTHON_ARCH: "32"
    - TOXENV: "2.6-nocover"
      TOXPYTHON: "C:\\Python26\\python.exe"
      WINDOWS_SDK_VERSION: "v7.0"
      PYTHON_HOME: "C:\\Python26"
      PYTHON_VERSION: "2.6"
      PYTHON_ARCH: "32"
    - TOXENV: "2.7"
      TOXPYTHON: "C:\\Python27\\python.exe"
      WINDOWS_SDK_VERSION: "v7.0"
      PYTHON_HOME: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
    - TOXENV: "2.7-nocover"
      TOXPYTHON: "C:\\Python27\\python.exe"
      WINDOWS_SDK_VERSION: "v7.0"
      PYTHON_HOME: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
init:
  - "ECHO %TOXENV%"
  - ps: "ls C:\\Python*"
install:
  - "powershell ci\\appveyor-bootstrap.ps1"
test_script:
  - "%PYTHON_HOME%\\Scripts\\tox --version"
  - "%PYTHON_HOME%\\Scripts\\virtualenv --version"
  - "%PYTHON_HOME%\\Scripts\\pip --version"
  - "%WITH_COMPILER% %PYTHON_HOME%\\Scripts\\tox"
after_test:
  - "IF \"%TOXENV:~-8,8%\" == \"-nocover\" %WITH_COMPILER% %TOXPYTHON% setup.py bdist_wheel"
artifacts:
  - path: dist\*
